### PR TITLE
fix: use correct options object & set fallback context

### PR DESCRIPTION
**Pull request by herschel666**
Hey, I have two fixes here. :-)

### CODE REVIEW

**Comment by olegstepura** [comment]
Could you please describe what it fixes

**Comment by herschel666** [comment]
When using the loader with `webpack@4.1.1` on `node@8.9.1` I'll get the following error:

```
TypeError: Cannot read property 'context' of undefined
```

My guess was, that this is related to treating the options as an instance variable, while it's actually a local variable. After fixing that, I got the following error:

```
TypeError: Path must be a string. Received undefined
```

This is because `options.context`, which is passed into `path.relative()`, is `undefined`. My take was to set the falback for `context` to `process.cwd()`.

An alternative approach would be to fall back to an empty string:

```diff
- this.emitFile(path.relative(options.context, content.outputFilePath), content.contents || [''], map);
+ this.emitFile(path.relative(options.context || '', content.outputFilePath), content.contents || [''], map);
```

What do you think?

**Comment by olegstepura** [comment]
Did you try to use `queryOptions` to define `options.context` to fix you issue?

**Comment by herschel666** [comment]
No, since it's not a required option parameter.

**Comment by unstubbable** [comment]
I'm also interested in this fix. In my opinion the proposed solution makes sense. Setting the `context` via query options does not work, unless at least the second part of this PR is accepted:

```diff
- this.emitFile(path.relative(this.options.context, content.outputFilePath), content.contents || [''], map);
+ this.emitFile(path.relative(options.context, content.outputFilePath), content.contents || [''], map);
```

**Comment by unstubbable** [comment]
Looking at other PRs (like [this one](https://github.com/webpack-contrib/worker-loader/pull/128/files) or [this one](https://github.com/webpack-contrib/file-loader/pull/234)), I think this is the correct fix:

```diff
- this.emitFile(path.relative(this.options.context, content.outputFilePath), content.contents || [''], map);
+ var context = options.context || this.context || this.rootContext;
+ this.emitFile(path.relative(context, content.outputFilePath), content.contents || [''], map);
```

And also initialising `options` with an empty object (`var options = {};`).

**Review by unstubbable — APPROVED** [review]
Looks good to me.

**Comment by herschel666** [comment]
@KingHenne man, you're fast! :-D

**Comment by olegstepura** [comment]
Ok, merged and released `0.0.12`

**Pull request merged**
